package br.com.sedec.sipaflore.enums;

public enum EnumTipoDocumentoAutorizacao {

    PROCURACAO,
    PROCURACAO_SIMPLES_ADVOGADO,
    ATA_ELEICAO_ADM_JUNTA_COMERCIAL,
    ATO_NOMEACAO_TITULAR_DIARIO_OFICIAL,
    IDENTIFICACAO_REPRESENTANTE_EMPRESA,
    DOCUMENTO_REPRESENTANTE_ESPOLIO,
    OUTRO

}
